export const GAME_CONFIG = {
  CANVAS_WIDTH: 500,
  CANVAS_HEIGHT: 600,
  MAX_CANVAS_WIDTH: 800,
  PLAYER_WIDTH: 40,
  PLAYER_HEIGHT: 40,
  BULLET_WIDTH: 8,
  BULLET_HEIGHT: 8,
  BULLET_SPEED: 30,
  ENEMY_SPEED: 1.0,
  ENEMY_SPAWN_INTERVAL: 2500,
  SAFETY_LINE_Y: 500,
  WORDS: [
    "hello",
    "world",
    "react",
    "typescript",
    "javascript",
    "code",
    "game",
    "play",
    "fun",
    "learn",
    "type",
    "word",
    "letter",
    "keyboard",
    "bullet",
    "shoot",
    "enemy",
    "player",
    "score",
    "lives",
  ],
};
